### ISSUE TITLE
multiple authors in author html meta-tag

### ISSUE THREAD

**Issue by dpprdan** [rstudio/rmarkdown#2191]
When trying to import a few bookdown books into Zotero, I noticed that for most books I get all authors into a single author field instead of one field per author. This happens because most multi-author books, including "[Rmarkdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)" and "[R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/)" provide only one author meta-tag. 
However, according to the [HTML spec](https://html.spec.whatwg.org/multipage/semantics.html#standard-metadata-names), the author meta tag "must be a free-form string giving the name of one of the page's authors." So multiple authors in one author meta tag is not valid html. 

The abovementioned books only provide one meta-tag because all authors are put into a single-string (see [Rmarkdown TDG](https://github.com/rstudio/rmarkdown-book/blob/ed81b894d5d2665d6ef4657c5840634512b97ff5/index.Rmd#L3) and [R Markdown Cookbook](https://github.com/yihui/rmarkdown-cookbook/blob/b7d818ccd5ff569194a67d1462a94f85716f5fa8/index.Rmd#L3)) instead of a [yaml array](https://www.w3schools.io/file/yaml-arrays/) (see "[Efficient R Programming](https://github.com/csgillespie/efficientR/blob/fcb509f850abf6f2f609b6dac4c5a06f2f322921/index.Rmd#L3)") in the yaml front-matter.

The same thing happens when providing multiple authors as a single string in e.g. `html_document()` (which is why I am posting the issue here instead of the bookdown repo). I.e. an rmarkdown `html_document` with 

```yaml
author: "Yihui Xie, Christophe Dervieux, Emily Riederer"
``` 

gives 

```yaml
<meta name="author" content="Yihui Xie, Christophe Dervieux, Emily Riederer" />
```

But is this really a bug? Maybe this is merely a user error, i.e. a failure to provide multiple authors  as a yaml array instead of a string? If multiple authors are provided as an array, rmarkdown and bookdown generate multiple author tags, see e.g. the source of [Efficient R Programming](https://csgillespie.github.io/efficientR/). But since most users make this mistake, including current rmarkdown authors/maintainer, I am wondering whether rmarkdown could provide a way for users to not make this mistake _this_ easily. (Efficient R Programming is the only book I found so far with multiple authors provided as a yaml array).

I see two possible solutions ATM

1. Make it easier for users to provide authors as an array instead of a single string, e.g. default to `author: ["firstname lastname"]` in all templates. IMO this is preferable, but there are at least two caveats. 
	a. I don't know whether this might have negative consequences for other output formats, e.g. PDF/latex? (There is a [test with two authors](https://github.com/rstudio/rmarkdown/blob/master/tests/rmd/two-authors.Rmd) for `pdf_document`, so maybe not?)
	b. The Rstudio "New R Markdown" dialogue would have to provide this new format as well.
2. Parse single string authors into a list before writing html author tags. This seems to be more error-prone, though. E.g. sometimes multiple authors are separated by "and", see [this example](https://github.com/rstudio/bookdown/blob/0de8f113fd1f8f9d8d140b754c5120eca1e27a0a/inst/examples/03-formats.Rmd#L8) from the bookdown book. 

Another thing to keep in mind is that users might want to use single strings because that renders the authors on a single line, 
> ![grafik](https://user-images.githubusercontent.com/1423562/126329607-30e6c830-95d6-4069-9c04-9cc854d886a3.png)

instead of multiple lines. 

> ![grafik](https://user-images.githubusercontent.com/1423562/126329497-a491ebae-95d0-46ff-a5b3-8d217fd05e46.png)

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [ ] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)? Still on R 4.0.5, though.

- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

<details>
<summary>Sessioninfo</summary>

R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041), RStudio 1.4.1717

Locale:
  LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
  LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

Package version:
  base64enc_0.1.3      digest_0.6.27        evaluate_0.14        fastmap_1.1.0        glue_1.4.2          
  graphics_4.0.5       grDevices_4.0.5      highr_0.9            htmltools_0.5.1.9005 jsonlite_1.7.2      
  knitr_1.33           magrittr_2.0.1       markdown_1.1         methods_4.0.5        mime_0.11           
  rlang_0.4.11.9000    rmarkdown_2.9.4      stats_4.0.5          stringi_1.7.3        stringr_1.4.0       
  tinytex_0.32         tools_4.0.5          utils_4.0.5          xfun_0.24            yaml_2.2.1          

Pandoc version: 2.11.4

</details>

**Comment by cderv** [comment]
Thanks for the report. This is a really interesting topic ! 

I think I mainly use a single author field in book project to have a single line in output. It never really occur to me that this could cause issue with tools that uses the `<author>` tags and other meta. I understand how this could create issues considering the spec mentions free-form but one author only.

@yihui do you have thoughts on this ? Asking because you mainly use a single author field in your book.

**Comment by yihui** [comment]
I don't have a strong opinion on this. We could use an array of author names in our books (e.g., the Definitive Guide and Cookbook). That should be fine for HTML output. I'm not sure about PDF output. Specifically, I don't know what the output would look like with Chapman & Hall's LaTeX class if the `author` field is an array. That's probably the reason why I used a single string.
